import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared/navbar";
import GlobalSpaceFooter from "@/components/shared/footer";
import "katex/dist/katex.min.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense } from "react";
import LayoutLoaderHandler from "@/components/shared/layout-loader-handler";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html
                lang="en"
                className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
            >
                <body className="min-h-full flex flex-col">
                    <Suspense fallback={null}>
                        <LayoutLoaderHandler />
                    </Suspense>
                    <Navbar />
                    {children}
                    <GlobalSpaceFooter />
                </body>
            </html>
        </ClerkProvider>
    );
}
