import { JSX } from "react";
import {
    FaCar,
    FaCode,
    FaHistory,
    FaDna,
    FaCalculator,
    FaGlobeAmericas,
    FaFlask,
    FaPalette,
    FaMicroscope,
    FaLaptopCode,
    FaGavel,
    FaMusic,
    FaBook,
    FaBusinessTime,
    FaUserTie,
    FaStethoscope,
    FaPlane,
    FaLanguage,
    FaAtom,
    FaChartLine,
    FaLandmark,
    FaShieldAlt,
    FaBrain,
    FaCamera,
    FaCoins,
    FaDatabase,
    FaGamepad,
    FaGlobe,
    FaSearch,
} from "react-icons/fa";

export interface SubjectType {
    id: number;
    key: string;
    icon: JSX.Element;
    color: string;
    label?: string;
    parentId?: string;
}

export const subjects: SubjectType[] = [
    { id: 1, key: "math", icon: <FaCalculator />, color: "#a78bfa" },
    { id: 2, key: "physics", icon: <FaMicroscope />, color: "#818cf8" },
    { id: 3, key: "chemistry", icon: <FaFlask />, color: "#2dd4bf" },
    { id: 4, key: "biology", icon: <FaDna />, color: "#34d399" },
    { id: 5, key: "history", icon: <FaHistory />, color: "#fbbf24" },
    { id: 6, key: "geography", icon: <FaGlobeAmericas />, color: "#38bdf8" },
    { id: 7, key: "literature", icon: <FaBook />, color: "#f472b6" },
    { id: 8, key: "mother_tongue", icon: <FaLanguage />, color: "#fb7185" },
    { id: 9, key: "english", icon: <FaGlobe />, color: "#6366f1" },
    { id: 10, key: "russian", icon: <FaLanguage />, color: "#ef4444" },
    { id: 11, key: "korean", icon: <FaLanguage />, color: "#3b82f6" },
    { id: 12, key: "german", icon: <FaLanguage />, color: "#f59e0b" },
    { id: 13, key: "it_code", icon: <FaCode />, color: "#60a5fa" },
    { id: 14, key: "fullstack", icon: <FaLaptopCode />, color: "#fb923c" },
    { id: 15, key: "cybersecurity", icon: <FaShieldAlt />, color: "#ef4444" },
    { id: 16, key: "database", icon: <FaDatabase />, color: "#22c55e" },
    { id: 17, key: "gamedev", icon: <FaGamepad />, color: "#ec4899" },
    { id: 18, key: "ai_machine_learning", icon: <FaAtom />, color: "#8b5cf6" },
    { id: 19, key: "driving", icon: <FaCar />, color: "#f87171" },
    { id: 20, key: "law", icon: <FaGavel />, color: "#94a3b8" },
    { id: 21, key: "medicine", icon: <FaStethoscope />, color: "#f43f5e" },
    { id: 22, key: "economics", icon: <FaChartLine />, color: "#10b981" },
    { id: 23, key: "accounting", icon: <FaCoins />, color: "#eab308" },
    {
        id: 24,
        key: "business_admin",
        icon: <FaBusinessTime />,
        color: "#64748b",
    },
    { id: 25, key: "interview_prep", icon: <FaUserTie />, color: "#475569" },
    { id: 26, key: "psychology", icon: <FaBrain />, color: "#d946ef" },
    { id: 27, key: "philosophy", icon: <FaLandmark />, color: "#a8a29e" },
    { id: 28, key: "art", icon: <FaPalette />, color: "#fb7185" },
    { id: 29, key: "music", icon: <FaMusic />, color: "#e879f9" },
    { id: 30, key: "photography", icon: <FaCamera />, color: "#06b6d4" },
    { id: 31, key: "logistics", icon: <FaPlane />, color: "#f97316" },
    { id: 32, key: "logic_iq", icon: <FaSearch />, color: "#ffffff" },
];

export const programmingLanguages: SubjectType[] = [
    {
        id: 101,
        key: "javascript",
        label: "JavaScript",
        parentId: "it_code",
        icon: <FaCode />,
        color: "#f7df1e",
    },
    {
        id: 102,
        key: "python",
        label: "Python",
        parentId: "it_code",
        icon: <FaCode />,
        color: "#3776ab",
    },
    {
        id: 103,
        key: "java",
        label: "Java",
        parentId: "it_code",
        icon: <FaCode />,
        color: "#007396",
    },
    {
        id: 104,
        key: "cpp",
        label: "C++",
        parentId: "it_code",
        icon: <FaCode />,
        color: "#00599c",
    },
    {
        id: 105,
        key: "php",
        label: "PHP",
        parentId: "it_code",
        icon: <FaCode />,
        color: "#777bb4",
    },
    {
        id: 106,
        key: "swift",
        label: "Swift",
        parentId: "it_code",
        icon: <FaCode />,
        color: "#f05138",
    },
    {
        id: 107,
        key: "go",
        label: "Go (Golang)",
        parentId: "it_code",
        icon: <FaCode />,
        color: "#00add8",
    },
];
